---

- name: IP ADDRESS
  debug: msg=" {{ ansible_default_ipv4.address }} List of plugins to install {{ plugins }}"

- name: COPY GROOVY SCRIPT TO TMP.
  template: src=plugin.groovy dest=/tmp/plugin.groovy

- name: INSTALL REQUIRED PLUGINS WHEN SECURITY IS ENABLED.
  shell: curl -u {{ jenkins.user }}:{{ jenkins.access_key }} -d "script=$(</tmp/plugin.groovy)" http://{{ ansible_default_ipv4.address }}:8080/scriptText
  register: with_security
  when: jenkins.user is defined and jenkins.access_key is defined

- name: INSTALL REQUIRED PLUGINS WHEN SECURITY IS NOT ENABLED.
  shell: curl -d "script=$(</tmp/plugin.groovy)" http://{{ ansible_default_ipv4.address }}:8080/scriptText
  register: without_security
  when: jenkins.user is not defined and jenkins.access_key is not defined

- debug: msg="{{ with_security }}"
- debug: msg="{{ without_security }}"
