---

- name: System Info
  debug: msg="OS={{ ansible_distribution }} RELEASE={{ ansible_distribution_major_version }} First test"

- name: INSTALL JENKINS
  yum: name=jenkins state=present

- block:
   - name: CHECK IF NFS MOUNT EXIST.
     stat: path={{ jenkins.mount }}/{{ jenkins.nfs_home }}
     register: result

   - name: CHECK IF DEFAULT HOME IS DIR OR LINK
     stat: path={{ jenkins.default_home }}
     register: check_result

   - debug: msg="{{ result }}"

   - debug: msg="{{ check_result }}"

   - name: MOVE DEFAULT HOME DIR TO NFS MOUNT
     command: mv {{ jenkins.default_home }} {{ jenkins.mount }}/{{ jenkins.nfs_home }}
     when: result.stat.isdir is not defined

   - name: MOVE DEFAULT HOME TO BACKUP DIR SINCE NFS ALREADY HAS HOME AVAILABLE.
     command: mv {{ jenkins.default_home }} {{ jenkins.path }}/{{ jenkins.service }}-bkp
     when: check_result.stat.isdir and result.stat.isdir is defined

   - name: CREATE LINK IN DEFAULT PATH TO POINT TO NFS MOUNT
     file: src={{ jenkins.mount }}/{{ jenkins.nfs_home }} dest={{ jenkins.default_home }} state=link owner=jenkins group=jenkins
  when: jenkins.mount is defined
- name: ENSURE JENKINS RUNNING AND ENABLED
  service: name={{ jenkins.serivce }} state=started enabled=yes
